export SHELL:=/bin/bash
.ONESHELL:

UNAME:=$(shell uname)

ifeq ($(UNAME), Darwin)
CONDASH:=Miniconda3-latest-MacOSX-arm64.sh
endif

ifeq ($(UNAME), Linux)
CONDASH:=Miniconda3-latest-Linux-x86_64.sh
endif

CNAME=scRNA
ifndef CNAME
$(error CNAME is not set)
endif

CONDAURL:=https://repo.anaconda.com/miniconda/$(CONDASH)

install: conda
	source conda/etc/profile.d/conda.sh
	conda create -y -n $(CNAME) -c conda-forge python=3.12
	conda activate $(CNAME)

	conda install -y conda-forge::r-seurat=4.4.0
	conda install -y r-tidyverse
	conda install -y bioconda::bioconductor-singler
	conda install -y bioconda::bioconductor-celldex
	conda install -y bioconda::bioconductor-singlecellexperiment

#
# Remember to install packages in install.R
#

conda:
	@set +e
	echo ">>> Setting up conda..."
	wget "$(CONDAURL)"
	bash "$(CONDASH)" -b -p conda
	rm -f "$(CONDASH)"

define help

Makefile to facilitate setup of conda environment for ARORA project

To install conda type
```
make -f <MAKEFILE> install CNAME={Name Of Env}
```
where <MAKEFILE> is the filename of this file

After installation to activate conda do:
```
source PATH_TO_INSALL_DIR/conda/etc/profile.d/conda.sh
conda activate arora
```
where PATH_TO_INSTALL_DIR is the path of the installation directory.


endef
export help
help:
	@printf "$$help"
.PHONY : help
